### ISSUE TITLE
update encointer dependencies

### ISSUE THREAD

**Issue by brenzi** [encointer/bazaar-web#11]
I observe the following error:
`TypeError: $C.rpc.communities.getAll is not a function`

guess we need to update dependencies as bazaar-web hasn't been touched in a while 

For testing:
There should be businesses and offerings registered on testnet gesell. verify with:
```
./bazaar.py -u wss://gesell.encointer.org -p 443 --cid u0qj94fxxJ6 list-businesses
connecting to remote chain:  wss://gesell.encointer.org
[BusinessData { url: "QmTTHFZ7roMRZD619Tn8mAttAmn2CnAh8NUXR4VocRvcfh", last_oid: 1 }, BusinessData { url: "QmWYjfdsScf2mBxKgGbBq822FzRNkB5nG6wjK2NKLw1Ewz", last_oid: 2 }]
./bazaar.py -u wss://gesell.encointer.org -p 443 --cid u0qj94fxxJ6 list-offerings
connecting to remote chain:  wss://gesell.encointer.org
[OfferingData { url: "QmVFGqk81v8yfBnAz3wUu38VLqrpidJjm9oH9fPrKikyjD" }]

```

**Comment by clangenb** [comment]
Dependencies updated and the connection to Gesell is functional. However, reading data from ipfs fails due to https://github.com/encointer/bazaar-web/issues/17.
