### ISSUE TITLE
publish bazaar-web with gh-pages and browse Gesell

### ISSUE THREAD

**Issue by brenzi** [encointer/bazaar-web#3]
* change endpoint to gesell.encointer.org
* use infura with a Github secret
* deploy with gH action (see explorer to see how)
* allow url config to test local environments too (localhost and local ipfs)

**Comment by anizeani** [comment]
why do I need infura with github secret? I don't add any files to ipfs, only cat?

**Comment by brenzi** [comment]
true. as long as we don't have much traffic, infura may accept our requests without credentials. we can add this later

**Comment by anizeani** [comment]
ok, besides infura credentials i have applied all the changes requested (see commits).
My questions are: 
- how should we test/create communities and businesses on encointer.gesell.org? (python scripts are written only for local node)
- what possible scenarios do we want for local and remote, right now we have: 
local: (ipfs local and local gesell node) and remote: infura ipfs and remote gesell node. 
is there a need for infura ipfs and local gesell node?

**Comment by anizeani** [comment]
in the meantime, python scripts where updated to also work with remote node. 
we have 3 szenarios: local/local, local chain/remote ipfs, remote chain/remote ipfs.
Publish with GA: do you mean the browser to be published on remote server, or the build process?
Because #2 is added the github workflow build

**Comment by brenzi** [comment]
done. but https://github.com/encointer/bazaar-web/issues/10
